plugins {
    id "maven-publish"
}

apply plugin: "net.fabricmc.fabric-loom"
apply plugin: "com.replaymod.preprocess"

int mcVersion = 0
preprocess {
    mcVersion = vars.get().get("MC")
    vars.put("MC", mcVersion)
}

version = project.mod_version
group = project.maven_group

base {
    archivesName = "${project.archives_base_name}-mc${project.property('dependencies.minecraft_version')}"
}

repositories {
    mavenCentral()
}

loom {
    splitEnvironmentSourceSets()

    mods {
        waylandfix {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    minecraft "com.mojang:minecraft:${project.property('dependencies.minecraft_version')}"
    implementation "net.fabricmc:fabric-loader:${project.loader_version}"
    implementation "net.fabricmc.fabric-api:fabric-api:${project.property('fabric_api_version')}"

    testImplementation platform("org.junit:junit-bom:5.13.4")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"
}

processResources {
    inputs.property "version", project.version
    inputs.property "minecraft_version", project.property('dependencies.minecraft_version')
    filesMatching("fabric.mod.json") {
        expand "version": project.version, "minecraft_version": project.property('dependencies.minecraft_version')
    }
}

tasks.withType(JavaCompile).configureEach {
    options.release = 25
}

tasks.withType(Test).configureEach {
    useJUnitPlatform()
}

java {
    withSourcesJar()
    sourceCompatibility = JavaVersion.VERSION_25
    targetCompatibility = JavaVersion.VERSION_25
}

jar {
    from(rootProject.file("LICENSE")) {
        rename { "${it}_${project.name}" }
    }
}

publishing {
    publications {
        create("mavenJava", MavenPublication) {
            from components.java
        }
    }
}
