org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=false
org.gradle.configuration-cache=false

loader_version=0.19.3
loom_version=1.17-SNAPSHOT
fabric_api_version_26_1_2=0.154.2+26.1.2
fabric_api_version_26_2=0.156.0+26.2
preprocessor_version=c5abb4fb12

mod_version=0.1.0-beta.3-dev
maven_group=dev.br0b
archives_base_name=waylandfix
